# Generated by Django 2.1.3 on 2020-03-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honeypot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='Honeypots/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='Honeypots/covers/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
