# Generated by Django 3.0.4 on 2020-04-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200330_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='honeypot',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='honeypot',
            old_name='pdf',
            new_name='source',
        ),
    ]
