# Generated by Django 2.1.3 on 2020-05-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='password',
            field=models.FileField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='honeypot',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='honeypot',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
