# Generated by Django 2.1.3 on 2020-05-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_honeypot_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Honeypot',
        ),
    ]
